dependencies:
  # - <organization/repo>@<version> 
  - smartcontractkit/chainlink-brownie-contracts@1.2.0

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0'

dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}